<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Account Statement</title>
    <style>
        body {
            font-family: 'Segoe UI', Arial, sans-serif;
            color: #0B2B40;
            background: #fff;
            margin: 0;
            padding: 30px;
            font-size: 12px;
        }

        h2 {
            text-align: center;
            color: #0B2B40;
            margin-bottom: 10px;
            text-transform: uppercase;
            letter-spacing: 1px;
        }

        h3 {
            text-align: center;
            margin-bottom: 10px;
            text-transform: uppercase;
            letter-spacing: 1px;
        }

        .summary {
            margin-bottom: 25px;
            border: 1px solid #dfe6ef;
            border-radius: 8px;
            padding: 15px;
            background: #f8fafc;
        }

        .summary p {
            margin: 4px 0;
            font-size: 13px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
            font-size: 11.5px;
        }

        th, td {
            border: 1px solid #d1d5db;
            padding: 8px;
            text-align: left;
        }

        th {
            background: #0B2B40;
            color: white;
            text-transform: uppercase;
            font-weight: 600;
            font-size: 11px;
        }

        tr:nth-child(even) {
            background: #f9fafb;
        }

        tr:hover {
            background: #eef4ff;
        }

        .status-successful {
            color: #0B2B40;
            font-weight: 600;
        }

        .status-pending {
            color: #555;
            font-style: italic;
        }

        .status-failed {
            color: #b91c1c;
            font-weight: 600;
        }

        footer {
            text-align: center;
            margin-top: 40px;
            font-size: 10px;
            color: #888;
        }
        .div1 {
            display: flex; 
            justify-content: center; 
            align-items: center; 
            font-size: 1.25rem;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="div1"><img src="{{ asset('apple-touch-icon1.png') }}" alt="Logo" class="w-20 md:w-28 mx-auto lg:mx-0" />
    <h3>SEPU SACCO</h3>
    </div>
    <h2>Account Statement</h2>

    <div class="summary">
        <p><strong>Name:</strong> {{ $account->member->first_name }} {{ $account->member->last_name }}</p>
        <p><strong>Account Type:</strong> {{ $account->account_type }}</p>
        <p><strong>Account No:</strong> {{ $account->account_number }}</p>
        <p><strong>Balance:</strong> KES {{ number_format($account->balance) }}</p>
        <p><strong>Period:</strong> {{ $period['from'] }} - {{ $period['to'] }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Date & Time</th>
                <th>Type</th>
                <th>Amount (KES)</th>
                <th>Balance After</th>
                <th>Status</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody>
            @foreach($transactions as $tx)
            <tr>
                <td>{{ $tx->created_at->format('d M Y, h:i A') }}</td>
                <td>{{ str_replace('_', ' ', ucfirst($tx->transaction_type)) }}</td>
                <td>{{ number_format($tx->amount) }}</td>
                <td>{{ number_format($tx->balance_after) }}</td>
                <td class="status-{{ strtolower($tx->status) }}">{{ ucfirst($tx->status) }}</td>
                <td>{{ $tx->description ?? '—' }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <footer>
        Generated by SEPU SACCO • {{ now()->format('d M Y, h:i A') }}
    </footer>
</body>
</html>
